### ISSUE TITLE
line break in title

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-about-w3c-process#2]
How WAI Develops Accessibility Standards through the W3C Process:
Milestones and Opportunities to Contribute

(assigning to Eric since not sure how you want it done)

**Comment by yatil** [comment]
Line breaks or subtitles are not supported at this time. Can you point me at a design iteration that has the subtitle in a way you like? Would the subtitle be above or beneath the main heading? I suppose we might want both variants. (and we likely want subtitles to be inside the h1 or not?
